blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('post/', include('post.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from .views import HomeView

app_name = 'core'
urlpatterns = [
    path('', HomeView.as_view(), name='blog_home'),
]

post/urls.py
from django.urls import path
from .views import PostView

app_name = 'post'
urlpatterns = [
    path('<int:pk>/', PostView.as_view(), name='blog_post'),
]

comments/models.py
from django.db import models
from django.contrib.auth.models import User
from post.models import Post

# Create your models here.


class Comment(models.Model):
    post = models.ForeignKey(to=Post, on_delete=models.CASCADE, null=True, blank=True)
    comment_name = models.CharField(max_length=45, default="Anonymous User")
    text = models.TextField(max_length=300)
    created_at = models.DateTimeField(auto_now_add=True, null=True, blank=True)

    def __str__(self):
        return self.text[:30] + "..."

core/models.py
from django.db import models

# Create your models here.

post/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Post(models.Model):
    title = models.CharField(max_length=50)
    created_at = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    lead = models.TextField(max_length=300, null=True, blank=True)
    content = models.TextField(max_length=1000)
    photo = models.ImageField(upload_to='post/img', null=True, blank=True)

    def __str__(self):
        return self.title

comments/forms.py
from django.forms import ModelForm
from .models import Comment


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['comment_name', 'text']

comments/views.py
from django.shortcuts import render

# Create your views here.

core/views.py
from django.shortcuts import render
from django.views import View
from post.models import Post

# Create your views here.


class HomeView(View):
    def get(self, request):
        posts = Post.objects.all()
        return render(request=request, template_name='core/home.html',
                      context={'posts': posts})

post/views.py
from django.contrib.auth.models import AnonymousUser, User
from django.shortcuts import render, redirect
from django.views import View
from .models import Post
from comments.models import Comment
from comments.forms import CommentForm
from django.shortcuts import get_object_or_404

# Create your views here.


class PostView(View):
    def get(self, request, pk):
        post = get_object_or_404(Post, pk=pk)
        comment_form = CommentForm()
        comments = Comment.objects.filter(post=pk)
        context = {
            'post': post,
            'comment_form': comment_form,
            'comments': comments,
        }
        return render(request, template_name='post/post.html',
                      context=context)

    def post(self, request, pk):
        post = get_object_or_404(Post, pk=pk)
        comment_form = CommentForm()
        comment_text = request.POST['text']

        if request.user == AnonymousUser:
            user = User.objects.get(username="anon")
        else:
            user = request.user

        post_comment = Post.objects.get(pk=pk)

        Comment.objects.create(post=post_comment, user=user, text=comment_text)
        comments = Comment.objects.filter(post=post)

        context = {
            'comments': comments,
            'post': post,
            'comment_form': comment_form,
        }
        return render(request, template_name='post/post.html',
                      context=context)

core/templates/core/base.html
{% load static %}

<!doctype html>
<html lang='pt-br'>

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <title>Pedro's Blog | Home</title>
</head>

<body>

<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
        <a class="navbar-brand" href="{% url 'core:blog_home' %}">Pedro's Blog</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'core:blog_home' %}">Home
                        <span class="sr-only">(current)</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Sobre</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Serviços</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Contato</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

<!-- Page Content -->
<div class="container">

    {% block content %}
    {% endblock %}
</div>
<!-- /.container -->

<!-- Footer -->
<footer class="py-5 bg-dark">
    <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; Pedro Marques 2019</p>
    </div>
    <!-- /.container -->
</footer>

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
</body>

</html>

core/templates/core/home.html
{% extends 'core/base.html' %}
{% load static %}
{% block content %}

    <div class="row">

        <!-- Blog Entries Column -->
        <div class="col-md-8">

            <h1 class="my-4">Seu blog
                <small>Escreva sobre o que deseja</small>
            </h1>

            {% for post in posts %}
                <!-- Blog Post -->
                <div class="card mb-4">
                    {% if post.photo %}
                        <img id="post-image" class="card-img-top" src="{{ post.photo.url }}" alt="{{ post.title }}">
                    {% else %}
                        <img class="card-img-top" src="http://placehold.it/750x300" alt="Card image cap">
                    {% endif %}
                    <div class="card-body">
                        <h2 class="card-title">{{ post.title }}</h2>
                        <p class="card-text">{{ post.lead }}</p>
                        <a href="{% url 'post:blog_post' post.id  %}" class="btn btn-primary">Read More &rarr;</a>
                    </div>
                    <div class="card-footer text-muted">
                        Posted on {{ post.created_at }}
                        <a href="#">{{ post.author.get_full_name }}</a>
                    </div>
                </div>
            {% empty %}
            {% endfor %}

            <!-- Pagination -->
            <ul class="pagination justify-content-center mb-4">
                <li class="page-item">
                    <a class="page-link" href="#">&larr; Older</a>
                </li>
                <li class="page-item disabled">
                    <a class="page-link" href="#">Newer &rarr;</a>
                </li>
            </ul>

        </div>

        <!-- Sidebar Widgets Column -->
        <div class="col-md-4">

            <!-- Search Widget -->
            <div class="card my-4">
                <h5 class="card-header">Search</h5>
                <div class="card-body">
                    <div class="input-group">
                        <input type="text" class="form-control" placeholder="Search for...">
                        <span class="input-group-btn">
                                <button class="btn btn-secondary" type="button">Go!</button>
                            </span>
                    </div>
                </div>
            </div>

            <!-- Categories Widget -->
            <div class="card my-4">
                <h5 class="card-header">Categories</h5>
                <div class="card-body">
                    <div class="row">
                        <div class="col-lg-6">
                            <ul class="list-unstyled mb-0">
                                <li>
                                    <a href="#">Web Design</a>
                                </li>
                                <li>
                                    <a href="#">HTML</a>
                                </li>
                                <li>
                                    <a href="#">Freebies</a>
                                </li>
                            </ul>
                        </div>
                        <div class="col-lg-6">
                            <ul class="list-unstyled mb-0">
                                <li>
                                    <a href="#">JavaScript</a>
                                </li>
                                <li>
                                    <a href="#">CSS</a>
                                </li>
                                <li>
                                    <a href="#">Tutorials</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>

            <!-- Side Widget -->
            <div class="card my-4">
                <h5 class="card-header">Side Widget</h5>
                <div class="card-body">
                    You can put anything you want inside of these side widgets. They are easy to use, and feature
                    the new Bootstrap 4 card containers!
                </div>
            </div>

        </div>

    </div>
    <!-- /.row -->
{% endblock %}

post/templates/post/post.html
{% extends 'core/base.html' %}
{% load static %}
{% load widget_tweaks %}
{% block content %}

    <div class="row">

        <!-- Post Content Column -->
        <div class="col-lg-8">

            <!-- Title -->
            <h1 class="mt-4">{{ post.title }}</h1>

            <!-- Author -->
            <p class="lead">
                by
                <a href="#">{{ post.author.get_full_name }}</a>
            </p>

            <hr>

            <!-- Date/Time -->
            <p>Posted on {{ post.created_at }}</p>

            <hr>


            <!-- Preview Image -->
            {% if post.photo %}
                <img class="img-fluid rounded" src="{{ post.photo.url }}" alt="">
            {% else %}
                <img class="img-fluid rounded" src="http://placehold.it/900x300" alt="">
            {% endif %}

            <hr>

            <!-- Post Content -->
            <p class="lead">{{ post.lead }}</p>

            <p>{{ post.content }}</p>

            <hr>

            <!-- Comments Form -->
            <div class="card my-4">
                <h5 class="card-header">Leave a Comment:</h5>
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <div class="form-group">
                             <span>Seu nome: </span> {% render_field comment_form.comment_name class="form-control" %}
                            {% render_field comment_form.text rows="3" class="form-control" %}
                        </div>
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </form>
                </div>
            </div>

            {% if data %}
                {{ data }}
            {% endif %}

            <!-- Single Comment -->

            {% for comment in comments %}
                <div class="media mb-4">
                    <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
                    <div class="media-body">
                        <h5 class="mt-0">{{ comment.comment_name }}</h5>
                        {{ comment.text }}
                    </div>
                </div>
            {% endfor %}

        </div>

        <!-- Sidebar Widgets Column -->
        <div class="col-md-4">

            <!-- Search Widget -->
            <div class="card my-4">
                <h5 class="card-header">Search</h5>
                <div class="card-body">
                    <div class="input-group">
                        <input type="text" class="form-control" placeholder="Search for...">
                        <span class="input-group-btn">
                                <button class="btn btn-secondary" type="button">Go!</button>
                            </span>
                    </div>
                </div>
            </div>

            <!-- Categories Widget -->
            <div class="card my-4">
                <h5 class="card-header">Categories</h5>
                <div class="card-body">
                    <div class="row">
                        <div class="col-lg-6">
                            <ul class="list-unstyled mb-0">
                                <li>
                                    <a href="#">Web Design</a>
                                </li>
                                <li>
                                    <a href="#">HTML</a>
                                </li>
                                <li>
                                    <a href="#">Freebies</a>
                                </li>
                            </ul>
                        </div>
                        <div class="col-lg-6">
                            <ul class="list-unstyled mb-0">
                                <li>
                                    <a href="#">JavaScript</a>
                                </li>
                                <li>
                                    <a href="#">CSS</a>
                                </li>
                                <li>
                                    <a href="#">Tutorials</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>

            <!-- Side Widget -->
            <div class="card my-4">
                <h5 class="card-header">Side Widget</h5>
                <div class="card-body">
                    You can put anything you want inside of these side widgets. They are easy to use, and feature
                    the new Bootstrap 4 card containers!
                </div>
            </div>

        </div>

    </div>
    <!-- /.row -->

{% endblock %}